name: Deploy a producciÃ³n

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Mostrar mensaje de inicio
        run: echo "Iniciando deploy a producciÃ³n..."

      - name: Mostrar secret enmascarado
        run: echo "Password de producciÃ³n: ${{ secrets.PROD_PASSWORD }}"


      - name: Simular deploy
        run: |
          echo "Desplegando app..."
          sleep 2
          echo "Deploy completado correctamente ðŸš€"
